---
title: "Análisis de variables"
author: "Jander C. M.,
         Lady D. V.,
         Anthony M. V.,
         Joel V. I."
format: html
---

# Diseño experimental
$$hi = /mu + ddp + tratamiento + ddp * tratamiento + plantas + e$$

# Cargar paquetes
```{r}
library(tidyverse)
library(googlesheets4)
library(emmeans)
library(multcomp)
library(multcompView)
library(knitr)
```

# Importar los datos
```{r}
url <- "https://docs.google.com/spreadsheets/d/1ttjzc3A3Mj1adlBxQa74_-kBxGZ4pHpfrKVYWctQJCs/edit?gid=67534688#gid=67534688"
gs<-url %>% as_sheets_id()
fb<- gs %>% range_read("fb")
str(fb)
```

## Convertir a factor
```{r}
fb <- fb %>%
  mutate(
    tratamiento = as_factor(tratamiento),
    ddp = as_factor(ddp),
    plantas = as_factor(plantas)
  )
str(fb)
```

# Análisis para altura
## ANOVA
```{r}
alt <- aov(altura ~ plantas + tratamiento * ddp, data = fb)
anova(alt)
```

## Comparación de medias
```{r}
emm_int <- emmeans(alt, ~ tratamiento * ddp)
cld_int <- cld(
  emm_int,
  adjust = "tukey",
  Letters = letters,
  alpha = 0.05
) %>%
  as_tibble() %>%
  mutate(
    .group = stringr::str_trim(.group)
  )
cld_int %>% kable()
```

## Gráfico
```{r}
ggplot(cld_int, aes(x = tratamiento, y = emmean, fill = ddp)) +
  geom_col(position = position_dodge(width = 0.8)) +
  geom_errorbar(
    aes(ymin = lower.CL, ymax = upper.CL),
    position = position_dodge(width = 0.8),
    width = 0.2
  ) +
  geom_text(
    aes(label = .group, y = upper.CL),
    position = position_dodge(width = 0.8),
    vjust = -0.4,
    size = 4
  ) +
   labs(
    x = "Tratamiento",
    y = "Altura (cm)",
    fill = "Días después de la plantación (ddp)",
    title = "Medias marginales (emmeans) y comparación de Tukey para la interacción de tratamientos por ddp"
 ) +
  theme_minimal(base_size = 12) +
  theme(
    plot.title = element_text(face = "bold"),
    legend.position = "top"
  )
```

# Analisis para longitud
## ANOVA
```{r}
long <- aov(longitud ~ plantas + tratamiento * ddp, data = fb)
anova(long)
```

## Comparación de medias
```{r}
emm_int <- emmeans(long, ~ tratamiento * ddp)
cld_int <- cld(
  emm_int,
  adjust = "tukey",
  Letters = letters,
  alpha = 0.05
) %>%
  as_tibble() %>%
  mutate(
    .group = stringr::str_trim(.group)
  )
cld_int %>% kable()
```

## Gráfico
```{r}
ggplot(cld_int, aes(x = tratamiento, y = emmean, fill = ddp)) +
  geom_col(position = position_dodge(width = 0.8)) +
  geom_errorbar(
    aes(ymin = lower.CL, ymax = upper.CL),
    position = position_dodge(width = 0.8),
    width = 0.2
  ) +
  geom_text(
    aes(label = .group, y = upper.CL),
    position = position_dodge(width = 0.8),
    vjust = -0.4,
    size = 4
  ) +
   labs(
    x = "Tratamiento",
    y = "Longitud (cm)",
    fill = "Días después de la plantación (ddp)",
    title = "Medias marginales (emmeans) y comparación de Tukey para la interacción de tratamientos por ddp"
 ) +
  theme_minimal(base_size = 12) +
  theme(
    plot.title = element_text(face = "bold"),
    legend.position = "top"
  )
```

# Análisis para hojas
## ANOVA
```{r}
hj <- aov(hojas ~ plantas + tratamiento * ddp, data = fb)
anova(hj)
```

## Comparación de medias
```{r}
emm_int <- emmeans(hj, ~ tratamiento * ddp)
cld_int <- cld(
  emm_int,
  adjust = "tukey",
  Letters = letters,
  alpha = 0.05
) %>%
  as_tibble() %>%
  mutate(
    .group = stringr::str_trim(.group)
  )
cld_int %>% kable()
```

## Gráfico
```{r}
ggplot(cld_int, aes(x = tratamiento, y = emmean, fill = ddp)) +
  geom_col(position = position_dodge(width = 0.8)) +
  geom_errorbar(
    aes(ymin = lower.CL, ymax = upper.CL),
    position = position_dodge(width = 0.8),
    width = 0.2
  ) +
  geom_text(
    aes(label = .group, y = upper.CL),
    position = position_dodge(width = 0.8),
    vjust = -0.4,
    size = 4
  ) +
   labs(
    x = "Tratamiento",
    y = "N° de hojas",
    fill = "Días después de la plantación (ddp)",
    title = "Medias marginales (emmeans) y comparación de Tukey para la interacción de tratamientos por ddp"
 ) +
  theme_minimal(base_size = 12) +
  theme(
    plot.title = element_text(face = "bold"),
    legend.position = "top"
  )
```

# Analisis para peso
## ANOVA
```{r}
ps <- aov(peso ~ plantas + tratamiento * ddp, data = fb)
anova(ps)
```

## Comparación de medias
```{r}
emm_int <- emmeans(ps, ~ tratamiento * ddp)
cld_int <- cld(
  emm_int,
  adjust = "tukey",
  Letters = letters,
  alpha = 0.05
) %>%
  as_tibble() %>%
  mutate(
    .group = stringr::str_trim(.group)
  )
cld_int %>% kable()
```

## Grafico
```{r}
ggplot(cld_int, aes(x = tratamiento, y = emmean, fill = ddp)) +
  geom_col(position = position_dodge(width = 0.8)) +
  geom_errorbar(
    aes(ymin = lower.CL, ymax = upper.CL),
    position = position_dodge(width = 0.8),
    width = 0.2
  ) +
  geom_text(
    aes(label = .group, y = upper.CL),
    position = position_dodge(width = 0.8),
    vjust = -0.4,
    size = 4
  ) +
   labs(
    x = "Tratamiento",
    y = "Peso de la planta en gramos",
    fill = "Días después de la plantación (ddp)",
    title = "Medias marginales (emmeans) y comparación de Tukey para la interacción de tratamientos por ddp"
 ) +
  theme_minimal(base_size = 12) +
  theme(
    plot.title = element_text(face = "bold"),
    legend.position = "top"
  )
```
